#!/usr/bin/expect
spawn ssh -q -o StrictHostKeyChecking=no admin@10.192.33.12
expect {
  timeout { send_user "\nFailed to get password prompt\n"; exit 1 }
  eof { send_user "\nSSH failure for $hostname\n"; exit 1 }
  "*assword"
}
send "infoblox\r"
expect "*>"
send "set support_access\r"
expect "*(y or n):"
send "y\r"

expect "*is this correct? (y or n):"
send "y\r"
expect "*>"
send "exit\r\n"

